export const allCountryLists = [
  "Australia",
  "Austria",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Faroe Islands",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Greenland",
  "Hungary",
  "Iceland",
  "Ireland",
  "Italy",
  "Japan",
  "Lithuania",
  "Maldives",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Virgin Islands (US)",
];

export const placeLists = [
  {
    continent: "North America",
    countries: ["Los Angeles", "San Francisco", "New York"],
  },
  {
    continent: "Europe",
    countries: ["France", "Finland", "United Kingdom", "Greece"],
  },
  {
    continent: "Asia",
    countries: ["Japan", "South Korea", "Philippines"],
  },
  {
    continent: "Australia",
    countries: ["Syndey", "Brisbane"],
  },
];
